
export const forumCategories = [
  "Pet Health & Wellness",
  "Dog Care & Medicine",
  "Jobs",
  "Scholarships",
  "Funding Opportunities",
  "Patnerships & Collaborations",
  "Cat Care & Medicine",
  "Small Animal Cases",
  "Livestock Health",
  "Poultry Health",
  "Diagnostics & Lab",
  "Drugs & Vaccines",
  "Nutrition & Feeding",
  "Breeding & Reproduction",
  "Zoonosis & Public Health",
  "Emergency & First Aid",
  "Surgery & Radiology",
  "Preventive Care",
  "Research & Innovation",
  "Case Discussions",
  "Animal Welfare",
  "Behavior & Training",
  "Vet Business Tips",
  "Vet Law & Policies",
  "Adoption & Rescue",
  "Marketplace",
  "Platform Updates",
];
