export { default as Hero11 } from './hero-1.png';
export { default as Hero12 } from './hero-2.jpeg';
export { default as Hero13 } from './hero-3.jpeg';
export { default as Mission1 } from './mission-1.png';
export { default as Focus1 } from './focus1.png';
export { default as Focus2 } from './focus2.png';
export { default as Focus3 } from './focus3.png';
export { default as Focus4 } from './focus4.png';
export { default as Focus5 } from './focus5.jpg';
export { default as Impact1 } from './impact1.jpg';
export { default as Impact2} from './impact2.jpg';