// Export all icons here
export { default as Sponsor1 } from './sponsor1.png';
export { default as Sponsor2 } from './sponsor2.png';
export { default as Sponsor3 } from './sponsor3.png';
export { default as Sponsor4 } from './sponsor4.png';
export { default as Sponsor5 } from './sponsor5.png';
export { default as Sponsor6 } from './sponsor6.png';
export { default as Sponsor7 } from './sponsor7.png';
export { default as Sponsor8 } from './sponsor8.png';
export { default as Sponsor9 } from './sponsor9.png';
export { default as Sponsor10 } from './sponsor10.png';
export { default as Sponsor11 } from './sponsor11.png';
export { default as Sponsor12 } from './sponsor12.png';
export { default as Sponsor13 } from './sponsor13.png';
export { default as Sponsor14 } from './sponsor14.png';
export { default as Sponsor15 } from './sponsor15.png';
export { default as Sponsor16 } from './sponsor16.png';
export { default as Sponsor17 } from './sponsor17.png';
export { default as Sponsor18 } from './sponsor18.png';